const products = [
  {     
    id: 1,
    name: 'Dior Sauvage Eau de Toilette',
    description: 'A bold and fresh fragrance with bergamot, pepper, and amberwood — perfect for men who exude confidence.',
    price: 109.99,
    img: 'https://fimgs.net/mdimg/perfume/375x500.26615.jpg',
    category: 'Men',
  },
  {
    id: 2,
    name: 'Chanel Coco Mademoiselle',
    description: 'A sophisticated floral fragrance with notes of orange, jasmine, and patchouli for a modern woman.',
    price: 124.99,
    img: 'https://fimgs.net/mdimg/perfume/375x500.82.jpg',
    category: 'Women',
  },
  {
    id: 3,
    name: 'Versace Eros',
    description: 'An intense scent blending mint, green apple, and tonka bean for a powerful masculine touch.',
    price: 89.99,
    img: 'https://fimgs.net/mdimg/perfume/375x500.17338.jpg',
    category: 'Men',
  },
  {
    id: 4,
    name: 'YSL Black Opium',
    description: 'A sensual mix of coffee, vanilla, and white flowers — energetic and irresistible.',
    price: 119.99,
    img: 'https://fimgs.net/mdimg/perfume/375x500.26025.jpg',
    category: 'Women',
  },
  {
    id: 5,
    name: 'Tom Ford Oud Wood',
    description: 'Exotic and smoky with rare oud, sandalwood, and amber — luxurious unisex fragrance.',
    price: 149.99,
    img: 'https://fimgs.net/mdimg/perfume/375x500.4366.jpg',
    category: 'Unisex',
  },
  {
    id: 6,
    name: 'Gucci Bloom Eau de Parfum',
    description: 'Rich floral fragrance with notes of jasmine, tuberose, and Rangoon creeper.',
    price: 104.99,
    img: 'https://fimgs.net/mdimg/perfume/375x500.43843.jpg',
    category: 'Women',
  },
  {
    id: 7,
    name: 'Creed Aventus',
    description: 'An iconic scent of pineapple, birch, and musk symbolizing success and elegance.',
    price: 299.99,
    img: 'https://fimgs.net/mdimg/perfume/375x500.9828.jpg',
    category: 'Men',
  },
  {
    id: 8,
    name: 'Jo Malone Wood Sage & Sea Salt',
    description: 'A refreshing fragrance evoking the coastal air with sage and sea salt notes.',
    price: 139.99,
    img: 'https://fimgs.net/mdimg/perfume/375x500.26636.jpg',
    category: 'Unisex',
  },
  {
    id: 9,
    name: 'Burberry Her',
    description: 'A vibrant, fruity fragrance with berries, jasmine, and musk — youthful and confident.',
    price: 99.99,
    img: 'https://fimgs.net/mdimg/perfume/375x500.50631.jpg',
    category: 'Women',
  },
  {
    id: 10,
    name: 'Armani Code',
    description: 'Warm and seductive notes of tonka bean, vanilla, and leather — timeless masculine scent.',
    price: 114.99,
    img: 'https://fimgs.net/mdimg/perfume/375x500.1042.jpg',
    category: 'Men',
  },
];

module.exports = products;
